# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vq7pClBNfSQnA_gW-IIJhcBLzq1jNP-P
"""

!pip install --upgrade -q streamlit opencv-python-headless scikit-image pandas matplotlib seaborn pillow numpy
!npm install -q localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import cv2
# import numpy as np
# import pandas as pd
# from skimage import filters, exposure
# import matplotlib.pyplot as plt
# from PIL import Image
# import os # Import os for path operations
# 
# st.set_page_config(page_title="Ultrasound Quality Analyzer", page_icon="🩺", layout="wide")
# 
# st.title("🩺 Ultrasound Image Quality Analysis Tool")
# st.markdown("**No-reference Image Quality Assessment for Medical Ultrasound**")
# 
# with st.sidebar:
#     st.header("Upload Image(s)")
#     uploaded_files = st.file_uploader("Choose ultrasound image(s)...",
#                                     type=["png", "jpg", "jpeg", "tif", "tiff", "bmp"],
#                                     accept_multiple_files=True)
# 
#     st.markdown("---")
#     st.info("Supported formats: PNG, JPG, TIFF, BMP")
# 
# # Prepare list of image sources to process
# image_sources_to_process = []
# all_reports_data = [] # To collect data for the combined report
# 
# if uploaded_files:
#     for file in uploaded_files:
#         image_sources_to_process.append({"type": "uploaded", "object": file, "name": file.name})
# else:
#     # Scan /content/ for image files if nothing is uploaded
#     current_dir_images = [f for f in os.listdir("/content/") if f.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp'))]
#     if current_dir_images:
#         st.info("No files uploaded. Automatically processing all detected images in `/content/`.")
#         for img_name in current_dir_images:
#             image_sources_to_process.append({"type": "local", "path": os.path.join("/content/", img_name), "name": img_name})
#     else:
#         st.info("👈 Upload an ultrasound image(s) from the sidebar to start analysis, or place images in `/content/`.")
# 
# if image_sources_to_process:
#     st.header("Batch Processing Results")
#     for i, item in enumerate(image_sources_to_process):
#         st.markdown(f"### Processing: {item['name']}")
#         img = None
#         image_name = item['name']
# 
#         try:
#             if item["type"] == "uploaded":
#                 image = Image.open(item["object"]).convert('L')
#             elif item["type"] == "local":
#                 image = Image.open(item["path"]).convert('L')
#             img = np.array(image)
#         except Exception as e:
#             st.error(f"Error loading image {image_name}: {e}")
#             continue
# 
#         col1, col2 = st.columns([3, 1])
#         with col1:
#             st.image(img, caption=f"Loaded: {image_name}", use_column_width=True, channels="gray")
#         with col2:
#             st.metric("Resolution", f"{img.shape[0]} × {img.shape[1]}")
#             st.metric("Mean Intensity", f"{img.mean():.2f}")
#             st.metric("Std (Noise)", f"{img.std():.2f}")
# 
#         def calculate_quality_metrics(image):
#             metrics = {}
#             metrics['Sharpness (Laplacian Variance)'] = cv2.Laplacian(image, cv2.CV_64F).var()
#             metrics['RMS Contrast'] = float(image.std())
# 
#             hist, _ = np.histogram(image.flatten(), bins=256, range=(0, 255))
#             hist = hist / hist.sum()
#             metrics['Entropy'] = float(-np.sum(hist * np.log2(hist + 1e-10)))
# 
#             signal = float(image.mean())
#             noise = float(image.std())
#             metrics['Estimated SNR (dB)'] = 20 * np.log10(signal / (noise + 1e-10))
# 
#             thresh = filters.threshold_otsu(image)
#             fg = image[image > thresh]
#             bg = image[image <= thresh]
#             if len(fg) > 0 and len(bg) > 0:
#                 metrics['Contrast-to-Noise Ratio (CNR)'] = float(
#                     (fg.mean() - bg.mean()) / (np.sqrt(fg.var() + bg.var()) + 1e-10))
#             else:
#                 metrics['Contrast-to-Noise Ratio (CNR)'] = 0.0
#             return metrics
# 
#         metrics = calculate_quality_metrics(img)
#         df_metrics = pd.DataFrame(list(metrics.items()), columns=["Metric", "Value"]).round(4)
# 
#         score = 0
#         comments = []
#         if metrics['Sharpness (Laplacian Variance)'] > 400:
#             score += 35
#             comments.append("✅ **Good Sharpness**")
#         elif metrics['Sharpness (Laplacian Variance)'] > 100:
#             score += 20
#             comments.append("⚠️ Moderate Sharpness")
#         else:
#             comments.append("❌ **Blurry Image**")
# 
#         if metrics['RMS Contrast'] > 35:
#             score += 30
#             comments.append("✅ **Good Contrast**")
#         else:
#             comments.append("⚠️ Low Contrast")
# 
#         if metrics['Estimated SNR (dB)'] > 14:
#             score += 35
#             comments.append("✅ **Acceptable SNR**")
#         else:
#             comments.append("❌ **High Noise**")
# 
#         st.markdown("---")
#         col_m1, col_m2 = st.columns([2, 1])
#         with col_m1:
#             st.subheader("📊 Quality Metrics")
#             st.dataframe(df_metrics, use_container_width=True, hide_index=True)
#         with col_m2:
#             st.subheader("🎯 Overall Quality")
#             st.metric("Quality Score", f"{score}/100")
#             for c in comments:
#                 st.write(c)
# 
#         st.markdown("---")
#         st.subheader("🔍 Visual Analysis")
#         fig, axes = plt.subplots(2, 3, figsize=(18, 10))
#         axes[0,0].imshow(img, cmap='gray'); axes[0,0].set_title('Original'); axes[0,0].axis('off')
#         edges = cv2.Canny(img, 30, 100)
#         axes[0,1].imshow(edges, cmap='gray'); axes[0,1].set_title('Edge Map'); axes[0,1].axis('off')
#         high_pass = cv2.subtract(img, cv2.GaussianBlur(img, (5,5), 0))
#         axes[0,2].imshow(high_pass, cmap='gray'); axes[0,2].set_title('Noise Map'); axes[0,2].axis('off')
#         eq = exposure.equalize_hist(img)
#         axes[1,0].imshow(eq, cmap='gray'); axes[1,0].set_title('Enhanced'); axes[1,0].axis('off')
#         axes[1,1].hist(img.ravel(), bins=256); axes[1,1].set_title('Histogram')
#         axes[1,2].axis('off')
#         plt.tight_layout()
#         st.pyplot(fig)
#         plt.close(fig) # Close the figure to prevent it from displaying in future Streamlit runs unexpectedly
# 
#         report_data = {"Image": image_name, **metrics, "Quality_Score": score}
#         all_reports_data.append(report_data)
#         st.markdown("***\n") # Visual separator between images
# 
#     # Combined report download for all images processed
#     if all_reports_data:
#         combined_report_df = pd.DataFrame(all_reports_data)
#         csv_combined = combined_report_df.to_csv(index=False)
#         st.sidebar.download_button(
#             "📥 Download Combined Report (CSV)",
#             csv_combined,
#             "ultrasound_batch_report.csv",
#             "text/csv"
#         )
# 
# else:
#     st.info("👈 Upload an ultrasound image(s) or place images in `/content/` to start analysis")

!pkill -f streamlit
!pkill -f localtunnel

import subprocess
import time

# Start Streamlit with extra flags to fix JS loading issues
subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port", "8501",
    "--server.headless", "true",
    "--server.enableCORS", "false",
    "--server.enableXsrfProtection", "false",
    "--browser.gatherUsageStats", "false"
])

time.sleep(10)

print("🚀 Opening app... Please wait 10-15 seconds")
print("After opening the link, do a **Hard Refresh** (Ctrl + Shift + R)")
!npx localtunnel --port 8501